version: "3.9"

services:
  db:
    image: mysql:8
    container_name: comments_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - comment_network

  redis:
    image: redis:7
    container_name: comments_redis
    ports:
      - "6379:6379"
    networks:
      - comment_network

  backend:
    build: ./backend/comment_systems
    container_name: comments_backend
    entrypoint:
      [
        "bash",
        "/app/wait-for-it.sh",
        "db:3306",
        "--",
        "sh",
        "-c",
        "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      ]
    volumes:
      - ./backend/comment_systems:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
    networks:
      - comment_network

  frontend:
    build: ./frontend/comments_systems
    container_name: comments_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/comments_systems:/app
    # environment:
    #   - VITE_API_BASE_URL=http://167.172.165.82:8000
    #   - VITE_WS_BASE_URL=ws://167.172.165.82:8000
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - comment_network

  celery:
    build: ./backend/comment_systems
    container_name: comments_celery
    command: celery -A comment_systems  worker --loglevel=info
    volumes:
      - ./backend/comment_systems:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - comment_network

  celery-beat:
    build: ./backend/comment_systems
    container_name: comments_celery_beat
    command: celery -A comment_systems beat --loglevel=info
    volumes:
      - ./backend/comment_systems:/app
    depends_on:
      - redis
      - backend
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    networks:
      - comment_network

volumes:
  mysql_data:

networks:
  comment_network:
